version: '3.8'

services:
  libra-twin-network:
    build:
      context: .
      dockerfile: Dockerfile.testnet
    ports:
      - "34597:34597"
    volumes:
      - libra-data:/root/.libra/data
    environment:
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:34597/v1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s

volumes:
  libra-data: