name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    
    - name: Build and start twin network container
      run: |
        docker build -t libra-twin-network -f Dockerfile.testnet .
        docker run -d -p 34597:34597 --name libra-twin-network libra-twin-network
        # Wait for the twin network to be available
        timeout 300 bash -c 'until curl -s http://127.0.0.1:34597/v1 > /dev/null; do sleep 5; done'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run TypeScript check
      run: npx tsc --noEmit
      
    - name: Run ESLint
      run: npx eslint . --ext .ts,.tsx
      
    - name: Run Jest tests
      run: npm test
      env:
        LIBRA_RPC_URL: http://127.0.0.1:34597/v1
        TEST_ACCOUNT: 9A710919B1A1E67EDA335269C0085C91
        TEST_TRANSACTION: 0xcf4776b92c291291e0ee31107ab5984acba3f3ed5a76b5406d8dcf22d1834d18
      
    - name: Install Cypress dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
        
    - name: Start Expo web server
      run: npm run web -- --no-dev --minify &
      env:
        LIBRA_RPC_URL: http://127.0.0.1:34597/v1
      
    - name: Wait for server to start
      run: npx wait-on http://localhost:8082 -t 60000
      
    - name: Run Cypress tests
      run: npx cypress run
      env:
        CYPRESS_twinNetworkRpc: http://127.0.0.1:34597/v1
        CYPRESS_testAccount: 9A710919B1A1E67EDA335269C0085C91
        CYPRESS_testTransaction: 0xcf4776b92c291291e0ee31107ab5984acba3f3ed5a76b5406d8dcf22d1834d18
      
    - name: Upload test coverage
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Stop twin network container
      if: always()
      run: docker stop libra-twin-network || true